### Створення звичайного користувача

POST http://localhost:5000/auth/registration
Content-Type: application/json

{
    "username": "petro",
    "password": "qwerty"
}

### створення користувача з певною роллю

POST http://localhost:5000/admin-panel/registration
Content-Type: application/json

{
    "username": "superadmin",
    "password": "superadmin",
    "role": "ADMIN"
}

###


POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}


###

POST http://localhost:5000/auth/logout

###

GET http://localhost:5000/auth/refresh
HttpOnlyCookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjEsInVzZXJuYW1lIjoiYWRtaW41Iiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzAwMzI0MDQ0LCJleHAiOjE3MDI5MTYwNDR9.dE0Ox4ao4mG3Ze2bdCNq8DLhUrVFWI5-81feDbYbVJw

###

GET http://localhost:5000/computers

###
GET http://localhost:5000/computers/100

###

POST http://localhost:5000/order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzAyMDYwMzc4LCJleHAiOjE3MDIwNjIxNzh9.fqZD33kQPNmxbnUyfDz6OArzPRKOjU29DPSM3jxM-aY

{
  "orderRecords": [
    {
      "computer_id": 1,
      "quantity": 2,
      "price": 450
    },
    {
      "computer_id": 2,
      "quantity": 4,
      "price": 220
    },
    {
      "computer_id": 5,
      "quantity": 1,
      "price": 100
    }
  ],
}